---
title: "data_preprocessing"
author: "Martine Lind Jensen"
date: "2025-04-01"
output: html_document
---
In this script the data pre-processing for the project "Why is play fun?" is presented. The output from this script is a final dataframe applicable for the analysis part.  

```{r}
pacman::p_load(tidyverse, readxl)
```

```{r loading data}
df <- read_excel("data_for_analysis/Data3.xlsx")
```

#Functions

```{r function make df as.numeric}
as_num <- function(df)  {
  df <- as.numeric(df)
}
```

#Make dataframe ready for linear modelling
- part 1 and part 2 
```{r part 1 function for cleaning data per trial}
#Make function for making the dataframe in long format for trial and also adding puzzle number as a variable.

addtrial <- function(df, trial) {
  t1 <- ifelse(trial == 1, "first", ifelse(trial == 2, "second", ifelse(trial == 3, "third", ifelse(trial == 4, "fourth", "x"))))
  t2_cho <- ifelse(trial == 1, 1, ifelse(trial == 2, 3, ifelse(trial == 3, 5, ifelse(trial == 4, 7, "x"))))
  t2_not <- ifelse(trial == 1, 2, ifelse(trial == 2, 4, ifelse(trial == 3, 6, ifelse(trial == 4, 8, "x"))))
  
  pref <- select(df, starts_with(t1) & ends_with("pref"))

  pref_inv <- ifelse(pref == "E", "H", ifelse(pref == "H", "E", NA))
  
  selected_cho1 <- df %>% 
    select(c("ID", "Age", "Gender", "Base_smiley"), contains(c(t1, t2_cho))) %>% 
    select(-contains("not")) %>% 
    add_column(Puzzle_no = t2_cho)
  
  selected_cho <- cbind(selected_cho1,pref)
  
  selected_not1 <- df %>% 
    select(c("ID", "Age", "Gender", "Base_smiley"), contains(c(t1, t2_not))) %>% 
    select(-contains("cho")) %>% 
    add_column(Puzzle_no = t2_not)
  
  selected_not <- cbind(selected_not1,pref_inv)
  
  colnames(selected_cho) <- c("ID", "Age", "Gender", "Base_smiley", "Pref_trial", "Time", "Rating", "Forced_choice_trial", "Start", "End", "Time_hms", "Puzzle_no", "Diff")
  
  colnames(selected_not) <- c("ID", "Age", "Gender", "Base_smiley", "Pref_trial", "Time", "Rating", "Forced_choice_trial", "Start", "End", "Time_hms", "Puzzle_no", "Diff")  
  new_df <- rbind(selected_cho, selected_not) %>% 
    add_column(Trial = trial)
  
  return(new_df)
}

```

```{r part 2 run through all 4 trials}
df_list <- list()

#Loop through trials 1 to 4
for (i in 1:4) {
  df_list[[i]] <- addtrial(df, i)
}

#Combine all dataframes
final_df <- do.call(rbind, df_list)

final_df <- final_df %>% mutate_at(c("Rating", "Base_smiley", "Time"), as_num)
```

```{r}
#Save dataframe 
write.csv(final_df, "data_for_analysis/why_play_is_fun_data2.csv")

```

